#!/bin/bash

echo "🗄️  Setting up Supabase Database for LeadExtract..."
echo ""

echo "📋 Steps to set up Supabase:"
echo ""
echo "1. Go to https://supabase.com"
echo "2. Click 'New Project'"
echo "3. Enter project details:"
echo "   - Name: leadextract-db"
echo "   - Database Password: (create a secure password)"
echo "   - Region: Choose closest to you (e.g., US East)"
echo "4. Wait for database to provision (2-3 minutes)"
echo ""
echo "5. Once created, go to:"
echo "   - Project Settings → API"
echo "   - Copy these values:"
echo "     • Project URL"
echo "     • anon/public key"
echo "     • service_role key (keep secret!)"
echo ""
echo "6. Go to SQL Editor"
echo "7. Copy the SQL from db/schema.sql"
echo "8. Paste and run the SQL"
echo "9. Verify tables are created"
echo ""
echo "🔑 Your Supabase credentials will look like:"
echo "   NEXT_PUBLIC_SUPABASE_URL=https://xxxxxxxxxxxx.supabase.co"
echo "   NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "   SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo ""
echo "🔐 Generate encryption key:"
echo "   openssl rand -base64 32"
echo ""
echo "🌐 After Vercel deployment, add these to Vercel Environment Variables:"
echo "   1. Go to Vercel Dashboard"
echo "   2. Select your project"
echo "   3. Go to Settings → Environment Variables"
echo "   4. Add all variables from .env.local.example"
echo ""
echo "✅ Done! Your full-stack app will be ready."